"""empty message

Revision ID: 18a4f1b667b8
Revises: 39b30c535810
Create Date: 2022-01-13 21:28:40.624685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '18a4f1b667b8'
down_revision = '39b30c535810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'confirmed_at')
    op.add_column('user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed_at')
    op.add_column('records', sa.Column('confirmed_at', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
