"""empty message

Revision ID: 39b30c535810
Revises: 5321f10305d2
Create Date: 2022-01-13 21:25:41.047286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b30c535810'
down_revision = '5321f10305d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'confirmed_at')
    # ### end Alembic commands ###
