"""empty message

Revision ID: 5321f10305d2
Revises: 763e689ae68a
Create Date: 2022-01-09 15:08:55.083229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5321f10305d2'
down_revision = '763e689ae68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated')
    op.drop_column('user', 'birthdate')
    # ### end Alembic commands ###
