"""empty message

Revision ID: 763e689ae68a
Revises: 830ce6bfea3a
Create Date: 2022-01-04 14:14:50.698978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '763e689ae68a'
down_revision = '830ce6bfea3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'gender')
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###
