"""empty message

Revision ID: 875e06199791
Revises: 6881e357a874
Create Date: 2022-01-16 23:31:26.703481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875e06199791'
down_revision = '6881e357a874'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('middle_name_test', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'middle_name_test')
    # ### end Alembic commands ###
