"""empty message

Revision ID: a4da65227a9c
Revises: 875e06199791
Create Date: 2022-01-16 23:33:41.664569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4da65227a9c'
down_revision = '875e06199791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'middle_name_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('middle_name_test', mysql.VARCHAR(collation='utf8_unicode_ci', length=50), nullable=True))
    # ### end Alembic commands ###
