"""empty message

Revision ID: fca3b6b763fa
Revises: 
Create Date: 2021-12-18 20:39:03.995570

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fca3b6b763fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('company_name', table_name='msfo_records')
    op.drop_index('slug', table_name='msfo_records')
    op.drop_table('msfo_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msfo_records',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('company_name', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('slug', mysql.VARCHAR(collation='utf8_unicode_ci', length=100), nullable=True),
    sa.Column('short_info', mysql.TEXT(collation='utf8_unicode_ci'), nullable=True),
    sa.Column('long_info', mysql.VARCHAR(collation='utf8_unicode_ci', length=300), nullable=True),
    sa.Column('updated', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8_unicode_ci',
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('slug', 'msfo_records', ['slug'], unique=False)
    op.create_index('company_name', 'msfo_records', ['company_name'], unique=False)
    # ### end Alembic commands ###
