"""empty message

Revision ID: ff540e5b2378
Revises: a4da65227a9c
Create Date: 2022-01-20 21:56:51.196263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff540e5b2378'
down_revision = 'a4da65227a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fs_uniquifier', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'user', ['fs_uniquifier'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'fs_uniquifier')
    # ### end Alembic commands ###
